export const SET_RATING = 'SET_RATING';
export const SET_USER = 'SET_USER';
export const SET_PERFORMANCE = 'SET_PERFORMANCE';
export const SET_RELOAD_FEEDBACK = 'SET_RELOAD_FEEDBACK';

// Start Auth
export const LOGIN_USER = 'LOGIN_USER';
// End Auth

// Start Notification
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
// End Notification

export const GET_COUNT_CALL_EMOTION = 'GET_COUNT_CALL_EMOTION';
export const GET_CALL_REPORT = 'GET_CALL_REPORT';
export const GET_GENERATE_SPEECH_REPORT = 'GET_GENERATE_SPEECH_REPORT';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_ALL_CALLS = 'GET_ALL_CALLS';
export const GET_CALL_VISUALIZER = 'GET_CALL_VISUALIZER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_CALL_COUNT_BY_DURATION = 'GET_CALL_COUNT_BY_DURATION';
export const GET_CALL_COUNT = 'GET_CALL_COUNT';
export const CLEAR_CALL_VISUALIZER = 'CLEAR_CALL_VISUALIZER';
export const GET_CALL_COUNT_BY_HOLD_VIOLATION =
	'GET_CALL_COUNT_BY_HOLD_VIOLATION';
export const GET_CALL_COMPOSITION = 'GET_CALL_COMPOSITION';
export const GET_CALL_COUNT_FOR_CARDS = 'GET_CALL_COUNT_FOR_CARDS';
export const GET_CALL_COUNT_FOR_VOICE_ENERGY_DEVIATION =
	'GET_CALL_COUNT_FOR_VOICE_ENERGY_DEVIATION';
export const GET_SETTING_CONFIGURATION = 'GET_SETTING_CONFIGURATION';
export const ADD_SETTING_CONFIGURATION = 'ADD_SETTING_CONFIGURATION';
export const GET_NEGATIVE_CALL_COUNT = 'GET_NEGATIVE_CALL_COUNT';

// Filter
export const GET_FROM_DATE = 'GET_FROM_DATE';
export const GET_TO_DATE = 'GET_TO_DATE';
export const GET_AGENT_NAME = 'GET_AGENT_NAME';
export const GET_IS_CALL_OPENED_WITH_COMPLIANCE =
	'GET_IS_CALL_OPENED_WITH_COMPLIANCE';
export const GET_IS_CALL_CLOSED_WITH_COMPLIANCE =
	'GET_IS_CALL_CLOSED_WITH_COMPLIANCE';
export const GET_IS_TOTAL_COMPLIANCE = 'GET_IS_TOTAL_COMPLIANCE';
export const GET_IS_SERVICE_ISSUE = 'GET_IS_SERVICE_ISSUE';
export const GET_IS_PRODUCT_ISSUE = 'GET_IS_PRODUCT_ISSUE';
export const SET_FROM_DATE = 'SET_FROM_DATE';
export const SET_TO_DATE = 'SET_TO_DATE';
export const SET_AGENT_NAME = 'SET_AGENT_NAME';
export const SET_IS_CALL_OPENED_WITH_COMPLIANCE =
	'SET_IS_CALL_OPENED_WITH_COMPLIANCE';
export const SET_IS_CALL_CLOSED_WITH_COMPLIANCE =
	'SET_IS_CALL_CLOSED_WITH_COMPLIANCE';
export const SET_IS_TOTAL_COMPLIANCE = 'SET_IS_TOTAL_COMPLIANCE';
export const SET_IS_SERVICE_ISSUE = 'SET_IS_SERVICE_ISSUE';
export const SET_IS_PRODUCT_ISSUE = 'SET_IS_PRODUCT_ISSUE';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const GET_AGENT_ACHIEVEMENT = 'GET_AGENT_ACHIEVEMENT';
export const SET_FILTER = 'SET_FILTER';
export const ADD_NEW_EVALUATION_QUESTION = 'ADD_NEW_EVALUATION_QUESTION';
export const GET_EVALUATION_QUESTIONS_OF_MANAGER = 'GET_EVALUATION_QUESTIONS_OF_MANAGER';
export const GET_EVALUATION_QUESTIONS_OF_QA = 'GET_EVALUATION_QUESTIONS_OF_QA';
export const DELETE_EVALUATION_QUESTION_BY_ID = 'DELETE_EVALUATION_QUESTION_BY_ID';
export const CALL_FOR_STT = 'CALL_FOR_STT';
