export const SET_RATING = 'SET_RATING';
export const SET_USER = 'SET_USER';
export const SET_PERFORMANCE = 'SET_PERFORMANCE';
export const SET_RELOAD_FEEDBACK = 'SET_RELOAD_FEEDBACK';

// Start Auth
export const LOGIN_USER = 'LOGIN_USER';
// End Auth

// Start Notification
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
// End Notification

export const GET_COUNT_CALL_EMOTION = 'GET_COUNT_CALL_EMOTION';
export const GET_CALL_REPORT = 'GET_CALL_REPORT';
export const GET_GENERATE_SPEECH_REPORT = 'GET_GENERATE_SPEECH_REPORT';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_ALL_CALLS = 'GET_ALL_CALLS';
export const GET_CALL_VISUALIZER = 'GET_CALL_VISUALIZER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_CALL_COUNT_BY_DURATION = 'GET_CALL_COUNT_BY_DURATION';
export const GET_CALL_COUNT = 'GET_CALL_COUNT';
export const CLEAR_CALL_VISUALIZER = 'CLEAR_CALL_VISUALIZER';
export const GET_CALL_COUNT_BY_HOLD_VIOLATION =
	'GET_CALL_COUNT_BY_HOLD_VIOLATION';
